#!/bin/sh
# wait until X is locked
# $Id: X11-wait,v 1.1.1.1 2005/01/19 16:56:15 evaleto Exp $

. /morphix/include.sh >/dev/null 2>&1

if [ -n "$WINDOWMANAGER" ]; then
    for i in 1 2 3 4 5 6 7 8 9 10
      do
      if [ -f /tmp/.X0-lock ]; then
	  break
	  sleep 1
      fi
    done
fi
    
