#!/bin/sh
# X-server shut down
# $Id: X11-shutdown,v 1.1.1.1 2004/09/24 15:27:16 mkalbere Exp $

. /morphix/include.sh

for i in $XSERVER; do
    killall -TERM $i 2> /dev/null && echo "X-Server shut down." && break
done
    
